- ros_topic_name: "/sensor/gps"
  gz_topic_name: "/wamv/sensors/gps"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

- ros_topic_name: "/sensor/imu"
  gz_topic_name: "/wamv/sensors/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu/mag"
  gz_topic_name: "/wamv/sensors/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/altimeter/data"
  gz_topic_name: "/wamv/sensors/altimeter"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS

- ros_topic_name: "/left_thrust_cmd"
  gz_topic_name: "/wamv/thrusters/left/thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/right_thrust_cmd"
  gz_topic_name: "/wamv/thrusters/right/thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
